name: Dev Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH Script
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd 
            ./deploy-front.sh
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}
